layout: stacked
style: dark
repository: karlof002/karlof002.github.io

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  sort_by options: stars
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  instagram: _aboudy30._
  stackoverflow: 12383291
  youtube: channel/UChtkyk3S6XM884EnZGe0npQ
